# Generated by Django 3.1.4 on 2020-12-28 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('designation', models.CharField(help_text='E.i, Nutrition', max_length=80, unique=True, verbose_name='designation')),
            ],
            options={
                'verbose_name': 'Monitoring Category',
                'verbose_name_plural': 'Monitoring Categories',
            },
        ),
        migrations.CreateModel(
            name='SolutionObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('designation', models.CharField(help_text='E.i, Fall Detection', max_length=80, unique=True, verbose_name='designation')),
            ],
            options={
                'verbose_name': 'Solution Objective',
                'verbose_name_plural': 'Solutions Objectives',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='E.i, Fall Detection', max_length=80, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional: Provide a description for your solution', max_length=350, verbose_name='Description')),
                ('category', models.ForeignKey(help_text='The monitoring category to which the solution belongs', on_delete=django.db.models.deletion.CASCADE, to='monitoring_solutions.monitoringcategory', verbose_name='Category')),
                ('objective', models.ForeignKey(help_text='The final objective of the solution in question', on_delete=django.db.models.deletion.CASCADE, to='monitoring_solutions.solutionobjective', verbose_name='Objective')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
    ]
