# Generated by Django 3.1.4 on 2020-12-28 16:39

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "monitoring_cat.json")
    call_command("loaddata", "solution_objectives.json")

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_solutions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
