# Generated by Django 3.1.4 on 2021-01-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_solutions', '0005_auto_20210102_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.ForeignKey(help_text='The monitoring category to which the solution belongs', on_delete=django.db.models.deletion.CASCADE, to='monitoring_solutions.monitoringcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='objective',
            field=models.ForeignKey(help_text='The final objective of the solution in question', on_delete=django.db.models.deletion.CASCADE, to='monitoring_solutions.solutionobjective', verbose_name='Objective'),
        ),
    ]
