# Generated by Django 3.1.4 on 2021-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_solutions', '0006_auto_20210102_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='sampleJsonSchema',
            field=models.JSONField(default={}, help_text='Define the Json Schema that should be used for the storage of the data sample', verbose_name='Json Schema for Sample'),
            preserve_default=False,
        ),
    ]
