# Generated by Django 3.1.7 on 2021-04-04 21:14

from django.db import migrations
from django.core.management import call_command

def load_solution_data(apps, schema_editor):
    call_command("loaddata", "solution.json")


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_solutions', '0007_solution_samplejsonschema'),
    ]

    operations = [
        migrations.RunPython(load_solution_data),
    ]
