# Generated by Django 3.1.4 on 2020-12-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guardian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='target_user',
            new_name='user_target',
        ),
    ]
