# Generated by Django 3.1.4 on 2020-12-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201222_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='guardians',
            new_name='user_guardians',
        ),
    ]
