# Generated by Django 3.1.4 on 2020-12-22 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201222_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='user_guardians',
            field=models.ManyToManyField(blank=True, related_name='_guardian_user_guardians_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
