# Generated by Django 3.1.4 on 2021-02-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_monitoring', '0003_auto_20210203_1502'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersolutions',
            constraint=models.UniqueConstraint(fields=('patient', 'solution'), name='patient to solution relation'),
        ),
    ]
