# Generated by Django 3.1.6 on 2021-02-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_monitoring', '0004_auto_20210203_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(help_text='Is the sample valid?', verbose_name='Is Valid')),
                ('collectedTimeStamp', models.DateTimeField(help_text='Time stamp at the time of collection of the data sample', verbose_name='Time Stamp of the collection')),
                ('userSolution', models.ForeignKey(help_text='The User Solution that the collected data belongs to', on_delete=django.db.models.deletion.CASCADE, to='user_monitoring.usersolutions', verbose_name='User Solution')),
            ],
            options={
                'verbose_name': 'Collected Data',
                'verbose_name_plural': 'Collected Data',
            },
        ),
    ]
